# Generated by Django 4.1.3 on 2022-11-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_img',
            field=models.ImageField(blank=True, upload_to='topics_images'),
        ),
    ]
