# Generated by Django 4.1.3 on 2022-11-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_topic_topic_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, upload_to='posts_images'),
        ),
    ]
