# Generated by Django 4.1.3 on 2022-11-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_post_img_alter_topic_topic_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=20)),
                ('following', models.CharField(max_length=20)),
            ],
        ),
    ]
