# Generated by Django 4.1.3 on 2022-11-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_rename_users_usersprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='user_image',
        ),
    ]
