# Generated by Django 4.1.3 on 2022-11-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_usersprofile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
