# Generated by Django 4.1.3 on 2022-11-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_usersprofile_user_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
