# Generated by Django 4.1.3 on 2022-11-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_usersprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
