# Generated by Django 4.1.3 on 2022-12-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_usersprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_body',
            field=models.TextField(blank=True),
        ),
    ]
